services:
  - type: web
    name: django-local-library
    runtime: python
    buildCommand: "./build_files.sh"
    startCommand: "gunicorn locallibrary.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: django_local_library_db
          property: connectionString

databases:
  - name: django_local_library_db
    databaseName: django_local_library
    user: django_local_library_user
